language: cpp
compiler: 
- gcc
os: 
- linux
before_install:
        - echo "no install"
before_script:
        - cd projects/linsh/dominion
script:
        - make runtests
after_success:
        - echo "success"
branches:
  only:
          master
notifications:
  email: false

env:
  global:
          - LANG="en_US.UTF-8"
