/* RANDOM TESTING */
The input string is an array of 6 random characters generated by the 
inputChar() function. 

The input chars is a bit more interesting. I started with randomly picking 
characters from the ascii table but that took much time to finish. Instead I 
picked from a list of chars that will trigger the state change and produce 
the 'reset\0' string. This produces the error message in 1.171.092 iterations
on the first run.

Even with only 15 chars on the list, this produces about 11.390.625 possible 
permutations, so it could take 10x longer in worst cases. 
